
clear AAC FSState controlParams FWControlParams FixedWingCommandBus ...
      FixedWingCtrlBus ForwardVelocityCutoff HoverMission R_LOOKAHEAD ...
      R_WAYPOINTTRANSITION ReferenceFilterDen ReferenceFilterNum ...
      RotorCntrlBus SensorAAFiltDen SensorAAFiltNum SensorType TestMode ...
      TuningMode Visualization controlMode controlParams dDataSectObj ...
      guidanceType iniRoll iniYaw initPitch mdl minPWM myDictionaryObj ...
      simTimeParam tiltIni tilt_max uavParam vIni

clear iniP iniQ iniR

sim_data = Simulink.data.dictionary.open('VTOLDynamicsData.sldd');
discardChanges(sim_data);

%.. saveChanges(sim_data)